[package]
name = "cubase-project-plugins"
version = "0.1.0"
edition = "2021"
description = "Displays plugins used in your Cubase projects along with the Cubase version the project was created with."
repository = "https://github.com/fgimian/cubase-project-plugins.rs"
readme = "README.md"
license = "MIT"
keywords = ["music-production", "cubase"]
categories = ["command-line-interface"]

[lints.clippy]
expect_used = "warn"
unwrap_used = "warn"
panic = "warn"
correctness = { level = "warn", priority = 1 }
pedantic = { level = "warn", priority = 1 }
nursery = { level = "warn", priority = 1 }
cargo = { level = "warn", priority = 1 }
too_many_lines = { level = "allow", priority = 2 }

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.17", features = ["derive"] }
colored = "2.1.0"
dirs = "5.0.1"
glob = "0.3.1"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.63"
toml = "0.8.19"

[dev-dependencies]
rstest = "0.22.0"
