[package]
name = "cubase-project-plugins"
version = "0.1.0"
edition = "2021"
description = "Determines which plugins are used in your Cubase projects. "
repository = "https://github.com/fgimian/cubase-project-plugins.rs"
readme = "README.md"
license = "MIT"
keywords = ["cubase"]
categories = ["command-line-interface"]

[dependencies]
clap = { version = "4.1.10", features = ["derive"] }
glob = "0.3.1"
memchr = "2.5.0"
serde = { version = "1.0.157", features = ["derive"] }
termcolor = "1.2.0"
toml = "0.7.3"

[profile.release]
lto = true
strip = true
codegen-units = 1
