[package]
name = "cubase-project-plugins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.21", features = ["derive"] }
glob = "0.3.0"
memchr = "2.5.0"
serde = { version = "1.0.144", features = ["derive"] }
termcolor = "1.1.3"
toml = "0.5.9"
