[package]
name = "cubase-project-plugins"
version = "0.1.0"
edition = "2021"
description = "Displays plugins used in your Cubase projects along with the Cubase version the project was created with."
repository = "https://github.com/fgimian/cubase-project-plugins.rs"
readme = "README.md"
license = "MIT"
keywords = ["cubase"]
categories = ["command-line-interface"]

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.2.7", features = ["derive"] }
colored = "2.1.0"
dirs = "5.0.1"
glob = "0.3.1"
serde = { version = "1.0.183", features = ["derive"] }
thiserror = "1.0.56"
toml = "0.8.8"

[dev-dependencies]
rstest = "0.19.0"
