[package]
name = "cubase-project-plugins"
version = "0.1.0"
edition = "2021"
description = "Displays plugins used in your Cubase projects along with the Cubase version the project was created with."
repository = "https://github.com/fgimian/cubase-project-plugins"
readme = "README.md"
license = "MIT"
keywords = ["music-production", "cubase"]
categories = ["command-line-interface"]

[lints.clippy]
expect_used = "warn"
unwrap_used = "warn"
panic = "warn"
correctness = { level = "warn", priority = 1 }
pedantic = { level = "warn", priority = 1 }
nursery = { level = "warn", priority = 1 }
cargo = { level = "warn", priority = 1 }

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
colored = "2.1.0"
dirs = "5.0.1"
glob = "0.3.1"
serde = { version = "1.0.215", features = ["derive"] }
thiserror = "2.0.3"
toml = "0.8.19"

[dev-dependencies]
rstest = "0.23.0"
similar-asserts = "1.6.0"

[build-dependencies]
clap = { version = "4.5.21", features = ["derive"] }
clap_complete = "4.5.38"
dirs = "5.0.1"
